/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT CanCard.cdb */

/*  Include Header Files  */
#include <std.h>
#include <prd.h>
#include <hst.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>
#include <mbx.h>
#include <sts.h>

#ifdef __cplusplus
extern "C" {
#endif

extern PRD_Obj PRD0;
extern PRD_Obj PRD1;
extern PRD_Obj PRD2;
extern HST_Obj RTA_fromHost;
extern HST_Obj RTA_toHost;
extern SWI_Obj PRD_swi;
extern SWI_Obj KNL_swi;
extern TSK_Obj TSK_idle;
extern TSK_Obj TSK0;
extern TSK_Obj TSK1;
extern TSK_Obj TSK2;
extern TSK_Obj TSK3;
extern TSK_Obj TSK4;
extern TSK_Obj TSK5;
extern LOG_Obj LOG_system;
extern MBX_Obj MBX0;
extern MBX_Obj MBX1;
extern MBX_Obj MBX2;
extern STS_Obj IDL_busyObj;


#ifdef __cplusplus
}
#endif /* extern "C" */
